name: Pipeline render-Flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: EC2 salah
      run: |
            echo "${{secrets.AWS_EC2_SALAH}}" >private_key && chmod 700 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@http://ec2-18-234-254-164.compute-1.amazonaws.com:5000"
            cd FlaskPython/;git pull;./iniciar_app.sh"
